# Generated by Django 3.2.6 on 2021-10-22 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=200, verbose_name='スクリプトの名前')),
                ('script', models.TextField(verbose_name='スクリプトを記述')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default=None, max_length=20, verbose_name='サーバーの名前')),
                ('server_ip', models.CharField(max_length=20, verbose_name='サーバーのIPアドレス')),
                ('rcon_port', models.CharField(max_length=6, verbose_name='RCONクライアントのポート番号')),
                ('query_port', models.CharField(max_length=6, verbose_name='Queryクライアントのポート番号')),
                ('passw', models.CharField(max_length=200, verbose_name='パスワード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Command_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.CharField(max_length=100, verbose_name='実行したコマンド')),
                ('return_text', models.TextField(max_length=1000, verbose_name='実行結果')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('q_flag', models.BooleanField(default=False, verbose_name='')),
                ('chat_flag', models.BooleanField(default=False, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
