# Generated by Django 3.2.6 on 2021-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='flag',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
