# Generated by Django 3.2.8 on 2021-10-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, verbose_name='名前')),
                ('code', models.TextField(max_length=1000, verbose_name='コード')),
                ('flag', models.BooleanField(default=True, verbose_name='')),
                ('code_interval', models.CharField(default=None, max_length=5, verbose_name='実行間隔')),
            ],
        ),
    ]
