# Generated by Django 3.2.6 on 2021-08-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='selecter',
            field=models.CharField(choices=[('1', 'Loop'), ('2', 'If')], default='1', max_length=1),
        ),
    ]
