# Generated by Django 3.2.6 on 2021-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0003_code_selecter'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='condition',
            field=models.CharField(choices=[('1', '1分おきに実行する'), ('2', '1秒おきに実行する')], default='1', max_length=1, verbose_name='起動トリガー'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='code',
            name='script_name',
            field=models.CharField(max_length=200, verbose_name='コードの名前'),
        ),
        migrations.AlterField(
            model_name='code',
            name='selecter',
            field=models.CharField(choices=[('1', 'Loop'), ('2', 'If')], default='1', max_length=1, verbose_name='実行の形式'),
        ),
    ]
