# Generated by Django 3.2.6 on 2021-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0004_auto_20210808_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=200, verbose_name='サーバーのIPアドレス')),
                ('selecter', models.CharField(max_length=6, verbose_name='RCONクライアントのポート番号')),
                ('condition', models.CharField(max_length=6, verbose_name='Queryクライアントのポート番号')),
                ('code', models.TextField(verbose_name='コード')),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='condition',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='code',
            name='selecter',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='2', max_length=1, verbose_name='実行の形式'),
        ),
    ]
