# Generated by Django 3.2.6 on 2021-08-09 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rconc', '0005_auto_20210809_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='code',
        ),
        migrations.RemoveField(
            model_name='config',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='config',
            name='script_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='selecter',
        ),
        migrations.AddField(
            model_name='config',
            name='server_name',
            field=models.CharField(default='',verbose_name="サーバーの名前",max_length=20)
        ),
        migrations.AddField(
            model_name='config',
            name='passw',
            field=models.CharField(default='', max_length=200, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='config',
            name='query_port',
            field=models.CharField(default='', max_length=6, verbose_name='Queryクライアントのポート番号'),
        ),
        migrations.AddField(
            model_name='config',
            name='rcon_port',
            field=models.CharField(default='', max_length=6, verbose_name='RCONクライアントのポート番号'),
        ),
        migrations.AddField(
            model_name='config',
            name='server_ip',
            field=models.CharField(default='', max_length=20, verbose_name='サーバーのIPアドレス'),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        
    ]
