# Generated by Django 3.2.6 on 2021-08-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0009_alter_config_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='passw',
            field=models.CharField(max_length=200, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='config',
            name='query_port',
            field=models.CharField(max_length=6, verbose_name='Queryクライアントのポート番号'),
        ),
        migrations.AlterField(
            model_name='config',
            name='rcon_port',
            field=models.CharField(max_length=6, verbose_name='RCONクライアントのポート番号'),
        ),
        migrations.AlterField(
            model_name='config',
            name='server_ip',
            field=models.CharField(max_length=20, verbose_name='サーバーのIPアドレス'),
        ),
    ]
