# Generated by Django 3.2.6 on 2021-08-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0010_auto_20210809_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='condition',
            field=models.CharField(choices=[('1', '1分おきに実行する'), ('2', '1秒おきに実行する')], default='1', max_length=10),
        ),
    ]
