# Generated by Django 3.2.6 on 2021-08-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0011_alter_code_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
