# Generated by Django 3.2.6 on 2021-08-09 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rconc', '0012_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=20, verbose_name='サーバーのIPアドレス')),
                ('rcon_port', models.CharField(max_length=6, verbose_name='RCONクライアントのポート番号')),
                ('query_port', models.CharField(max_length=6, verbose_name='Queryクライアントのポート番号')),
                ('passw', models.CharField(max_length=200, verbose_name='パスワード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
