# Generated by Django 3.2.6 on 2021-08-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0014_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='server_name',
            field=models.CharField(default=None, max_length=20, verbose_name='サーバーの名前'),
        ),
    ]
