# Generated by Django 3.2.6 on 2021-08-10 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rconc', '0015_config_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='condition',
            field=models.CharField(choices=[('1', '1分おきに実行する'), ('2', '1秒おきに実行する')], default='1', max_length=10, verbose_name='実行間隔'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.TextField(verbose_name='スクリプトを記述'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_name',
            field=models.CharField(max_length=200, verbose_name='スクリプトの名前'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default=None, max_length=20, verbose_name='プロファイルの名前')),
                ('server_ip', models.CharField(max_length=20, verbose_name='サーバーのIPアドレス')),
                ('rcon_port', models.CharField(max_length=6, verbose_name='RCONクライアントのポート番号')),
                ('query_port', models.CharField(max_length=6, verbose_name='Queryクライアントのポート番号')),
                ('script', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
