# Generated by Django 3.2.6 on 2021-08-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0017_auto_20210810_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='condition',
            field=models.CharField(default='1', max_length=10, verbose_name='実行間隔'),
        ),
    ]
