# Generated by Django 3.2.6 on 2021-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0018_alter_code_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passw',
            field=models.CharField(default=None, max_length=200, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
