# Generated by Django 3.2.6 on 2021-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0021_alter_command_log_return_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_log',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
