# Generated by Django 3.2.6 on 2021-09-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0025_alter_command_log_q_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command_log',
            old_name='q_flag',
            new_name='query_flag_bool',
        ),
    ]
