# Generated by Django 3.2.6 on 2021-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0026_rename_q_flag_command_log_query_flag_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command_log',
            name='query_flag_bool',
            field=models.BooleanField(),
        ),
    ]
