# Generated by Django 3.2.6 on 2021-09-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0027_alter_command_log_query_flag_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command_log',
            name='query_flag_bool',
        ),
    ]
