# Generated by Django 3.2.6 on 2021-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0028_remove_command_log_query_flag_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_log',
            name='q_flag',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
