# Generated by Django 3.2.5 on 2021-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0029_command_log_q_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_log',
            name='chat_flag',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='command_log',
            name='return_text',
            field=models.TextField(max_length=1000, verbose_name='実行結果'),
        ),
    ]
