# Generated by Django 3.2.5 on 2021-10-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0030_auto_20211007_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
