# Generated by Django 3.2.6 on 2021-10-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rconc', '0030_auto_20211007_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, verbose_name='名前')),
                ('code', models.TextField(max_length=1000, verbose_name='実行結果')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
